In [1]:
import pandas as pd

# Load data
df = pd.read_csv("forcast_demand_for_trolley.csv")

In [2]:
df.head()

   historyId  trolleyId  geozoneId  geolayerId        date      time
0          1          1         11           7  2026-03-04  13:35:04
1          3          1         11           7  2026-03-04  13:37:14
2          8          1         11           7  2026-03-04  13:40:18
3         16          1         11           7  2026-03-04  13:42:16
4         20          1         11           7  2026-03-04  13:44:23

In [6]:
# Combine date + time
df['datetime'] = pd.to_datetime(
    df['date'] + ' ' + df['time'],
    format='%Y-%m-%d %H:%M:%S'
)

In [8]:
df.head()

,historyId,trolleyId,geozoneId,geolayerId,date,time,datetime
0,1,1,11,7,2026-03-04,13:35:04,2026-03-04 13:35:04
1,3,1,11,7,2026-03-04,13:37:14,2026-03-04 13:37:14
2,8,1,11,7,2026-03-04,13:40:18,2026-03-04 13:40:18
3,16,1,11,7,2026-03-04,13:42:16,2026-03-04 13:42:16
4,20,1,11,7,2026-03-04,13:44:23,2026-03-04 13:44:23

In [9]:
# Sort
df = df.sort_values(['trolleyId', 'datetime']).reset_index(drop=True)

df.head()

,historyId,trolleyId,geozoneId,geolayerId,date,time,datetime
0,1,1,11,7,2026-03-04,13:35:04,2026-03-04 13:35:04
1,3,1,11,7,2026-03-04,13:37:14,2026-03-04 13:37:14
2,8,1,11,7,2026-03-04,13:40:18,2026-03-04 13:40:18
3,16,1,11,7,2026-03-04,13:42:16,2026-03-04 13:42:16
4,20,1,11,7,2026-03-04,13:44:23,2026-03-04 13:44:23

# STEP 2: Create "movement change" flag

In [11]:
# Detect geozone change
df['prev_geozone'] = df.groupby('trolleyId')['geozoneId'].shift(1)

df['zone_changed'] = (df['geozoneId'] != df['prev_geozone']).astype(int)

# First row per trolley must be start
df['zone_changed'] = df['zone_changed'].fillna(1)

In [12]:
df.head()

,historyId,trolleyId,geozoneId,geolayerId,date,time,datetime,prev_geozone,zone_changed
0,1,1,11,7,2026-03-04,13:35:04,2026-03-04 13:35:04,NaN,1
1,3,1,11,7,2026-03-04,13:37:14,2026-03-04 13:37:14,11.0,0
2,8,1,11,7,2026-03-04,13:40:18,2026-03-04 13:40:18,11.0,0
3,16,1,11,7,2026-03-04,13:42:16,2026-03-04 13:42:16,11.0,0
4,20,1,11,7,2026-03-04,13:44:23,2026-03-04 13:44:23,11.0,0

# STEP 3: Assign segment IDs

In [13]:
df['segment_id'] = df.groupby('trolleyId')['zone_changed'].cumsum()

In [14]:
df.head()

,historyId,trolleyId,geozoneId,geolayerId,date,time,datetime,prev_geozone,zone_changed,segment_id
0,1,1,11,7,2026-03-04,13:35:04,2026-03-04 13:35:04,NaN,1,1
1,3,1,11,7,2026-03-04,13:37:14,2026-03-04 13:37:14,11.0,0,1
2,8,1,11,7,2026-03-04,13:40:18,2026-03-04 13:40:18,11.0,0,1
3,16,1,11,7,2026-03-04,13:42:16,2026-03-04 13:42:16,11.0,0,1
4,20,1,11,7,2026-03-04,13:44:23,2026-03-04 13:44:23,11.0,0,1

# STEP 4: Create interval dataset

In [ ]:
interval_df = df.groupby(['trolleyId', 'segment_id', 'geozoneId']).agg(
    start_time=('datetime', 'min'),
    end_time=('datetime', 'max')
).reset_index()

# Duration
interval_df['duration_min'] = (
    (interval_df['end_time'] - interval_df['start_time'])
    .dt.total_seconds() / 60
)

,trolleyId,segment_id,geozoneId,start_time,end_time,duration_min
0,1,1,11,2026-03-04 13:35:04,2026-03-04 13:51:17,16.216667
1,1,2,0,2026-03-04 13:57:33,2026-03-04 13:57:33,0.000000
2,1,3,2,2026-03-04 14:01:24,2026-03-04 14:13:10,11.766667
3,1,4,0,2026-03-04 14:22:53,2026-03-04 14:22:53,0.000000
4,1,5,3,2026-03-04 14:29:35,2026-03-04 14:40:16,10.683333

In [18]:
interval_df.tail(50)

,trolleyId,segment_id,geozoneId,start_time,end_time,duration_min
21342,500,9,1,2026-05-03 17:13:22,2026-05-03 17:13:22,0.000000
21343,500,10,16,2026-05-03 17:28:06,2026-05-03 23:02:39,334.550000
21344,500,11,1,2026-05-03 23:17:50,2026-05-03 23:32:40,14.833333
21345,500,12,0,2026-05-04 02:23:33,2026-05-04 02:53:23,29.833333
21346,500,13,6,2026-05-04 03:41:52,2026-05-04 03:41:52,0.000000
21347,500,14,17,2026-05-04 03:57:07,2026-05-04 03:57:07,0.000000
21348,500,15,16,2026-05-04 04:12:07,2026-05-10 15:32:56,9320.816667
21349,500,16,1,2026-05-10 16:27:59,2026-05-10 16:27:59,0.000000
21350,500,17,18,2026-05-10 16:43:52,2026-05-10 23:27:27,403.583333
21351,500,18,20,2026-05-10 23:42:18,2026-05-11 00:12:08,29.833333
21352,500,19,1,2026-05-11 00:18:32,2026-05-11 02:39:50,141.300000
21353,500,20,18,2026-05-11 03:51:05,2026-05-11 04:44:28,53.383333
21354,501,1,16,2026-04-30 07:41:07,2026-04-30 07:58:45,17.633333
21355,501,2,17,2026-04-30 08:08:49,2026-04-30 08:25:23,16.566667
21356,501,3,16,2026-04-30 08:29:44,2026-04-30 14:00:07,330.383333
21357,501,4,20,2026-04-30 14:15:06,2026-04-30 14:15:06,0.000000
21358,501,5,1,2026-04-30 14:30:42,2026-04-30 18:44:38,253.933333
21359,501,6,16,2026-04-30 21:07:00,2026-04-30 22:21:12,74.200000
21360,501,7,0,2026-05-01 02:50:44,2026-05-01 07:05:19,254.583333
21361,501,8,17,2026-05-01 07:20:29,2026-05-01 07:20:29,0.000000
21362,501,9,16,2026-05-01 07:35:42,2026-05-01 10:31:53,176.183333
21363,501,10,0,2026-05-01 11:14:31,2026-05-01 11:14:31,0.000000
21364,501,11,16,2026-05-01 11:29:17,2026-05-01 13:52:49,143.533333
21365,501,12,0,2026-05-01 14:10:12,2026-05-01 14:10:12,0.000000
21366,501,13,17,2026-05-01 14:25:16,2026-05-01 16:54:42,149.433333
21367,501,14,16,2026-05-01 17:16:32,2026-05-01 17:16:32,0.000000
21368,501,15,18,2026-05-01 17:45:40,2026-05-02 05:49:18,723.633333
21369,501,16,16,2026-05-02 06:04:10,2026-05-02 08:15:11,131.016667
21370,501,17,0,2026-05-02 16:12:06,2026-05-02 16:12:06,0.000000
21371,501,18,16,2026-05-02 16:26:53,2026-05-03 07:10:07,883.233333
21372,501,19,18,2026-05-03 08:01:25,2026-05-03 12:14:26,253.016667
21373,501,20,16,2026-05-03 16:27:55,2026-05-04 14:44:13,1336.300000
21374,501,21,0,2026-05-04 14:59:02,2026-05-04 14:59:02,0.000000
21375,501,22,16,2026-05-04 15:14:10,2026-05-04 15:41:16,27.100000
21376,501,23,17,2026-05-04 15:56:00,2026-05-05 05:29:49,813.816667
21377,501,24,16,2026-05-05 05:34:00,2026-05-05 08:43:11,189.183333
21378,501,25,18,2026-05-05 16:15:07,2026-05-06 16:50:42,1475.583333
21379,501,26,16,2026-05-06 17:32:01,2026-05-07 10:01:27,989.433333
21380,501,27,18,2026-05-07 17:01:41,2026-05-09 06:34:59,2253.300000
21381,501,28,16,2026-05-09 06:49:44,2026-05-09 07:19:49,30.083333
21382,501,29,1,2026-05-09 07:35:54,2026-05-09 07:35:54,0.000000
21383,501,30,0,2026-05-09 08:28:45,2026-05-09 09:15:25,46.666667
21384,501,31,17,2026-05-09 09:30:38,2026-05-09 09:30:38,0.000000
21385,501,32,16,2026-05-09 09:45:37,2026-05-09 18:04:10,498.550000
21386,501,33,17,2026-05-09 20:52:36,2026-05-10 02:38:14,345.633333
21387,501,34,16,2026-05-10 02:53:19,2026-05-10 21:07:32,1094.216667
21388,501,35,0,2026-05-10 21:22:25,2026-05-10 22:10:46,48.350000
21389,501,36,16,2026-05-10 22:25:50,2026-05-11 00:23:53,118.050000
21390,501,37,0,2026-05-11 02:34:52,2026-05-11 03:46:32,71.666667
21391,501,38,24,2026-05-11 04:17:19,2026-05-11 04:32:24,15.083333

In [19]:
interval_df.to_csv("duration_min.csv",index=False)

In [20]:
interval_df['hour'] = interval_df['start_time'].dt.hour
interval_df['day'] = interval_df['start_time'].dt.day
interval_df['weekday'] = interval_df['start_time'].dt.weekday
interval_df['is_weekend'] = interval_df['weekday'].isin([5,6]).astype(int)

In [21]:
interval_df.head()

,trolleyId,segment_id,geozoneId,start_time,end_time,duration_min,hour,day,weekday,is_weekend
0,1,1,11,2026-03-04 13:35:04,2026-03-04 13:51:17,16.216667,13,4,2,0
1,1,2,0,2026-03-04 13:57:33,2026-03-04 13:57:33,0.000000,13,4,2,0
2,1,3,2,2026-03-04 14:01:24,2026-03-04 14:13:10,11.766667,14,4,2,0
3,1,4,0,2026-03-04 14:22:53,2026-03-04 14:22:53,0.000000,14,4,2,0
4,1,5,3,2026-03-04 14:29:35,2026-03-04 14:40:16,10.683333,14,4,2,0

In [22]:
# Count trolleys per zone per hour
demand_df = interval_df.groupby(['geozoneId', 'hour']).agg(
    trolley_count=('trolleyId', 'nunique'),
    avg_duration=('duration_min', 'mean')
).reset_index()

In [24]:
demand_df.head(50)

    geozoneId  hour  trolley_count  avg_duration
0           0     0             93     40.458683
1           0     1            104     35.911640
2           0     2            201     69.944611
3           0     3            118     82.604555
4           0     4             92     30.149377
5           0     5            135     29.862828
6           0     6            148     21.931658
7           0     7            163     30.239528
8           0     8            143     29.218866
9           0     9            120     27.324717
10          0    10            126     90.239135
11          0    11            123     53.363444
12          0    12            112     22.129231
13          0    13            117     76.746578
14          0    14            170     29.868636
15          0    15            161     33.575641
16          0    16            133     21.518307
17          0    17            101     22.732697
18          0    18             48     24.098457
19          0    19             41     46.057843
20          0    20             66    188.346930
21          0    21            114    110.503266
22          0    22             86     95.738889
23          0    23             79     34.888246
24          1     0             78    178.583716
25          1     1             85    216.905442
26          1     2             64     58.615962
27          1     3             68     74.626042
28          1     4             62    182.443775
29          1     5             82    115.282828
30          1     6             81    113.570962
31          1     7             99    105.422934
32          1     8             94    111.771250
33          1     9             78     93.965326
34          1    10             86     77.384708
35          1    11             93     83.330992
36          1    12             84    226.258160
37          1    13             79    103.681228
38          1    14            193     62.578377
39          1    15            123     32.461976
40          1    16            112     19.026139
41          1    17             85    103.716667
42          1    18             35     95.781667
43          1    19             23     71.876000
44          1    20             53     41.429353
45          1    21             64    135.579958
46          1    22             58    158.464899
47          1    23             59    133.743939
48          2     0              1    279.200000
49          2     2              2      0.000000

In [25]:
demand_df = demand_df.sort_values(['geozoneId', 'hour'])

# Lag features
demand_df['lag_1'] = demand_df.groupby('geozoneId')['trolley_count'].shift(1)
demand_df['lag_2'] = demand_df.groupby('geozoneId')['trolley_count'].shift(2)

# Rolling mean
demand_df['rolling_mean'] = demand_df.groupby('geozoneId')['trolley_count']\
    .transform(lambda x: x.rolling(3).mean())

In [26]:
demand_df.head()

   geozoneId  hour  trolley_count  avg_duration  lag_1  lag_2  rolling_mean
0          0     0             93     40.458683    NaN    NaN           NaN
1          0     1            104     35.911640   93.0    NaN           NaN
2          0     2            201     69.944611  104.0   93.0    132.666667
3          0     3            118     82.604555  201.0  104.0    141.000000
4          0     4             92     30.149377  118.0  201.0    137.000000

In [27]:
final_df = demand_df.dropna()

X = final_df[['geozoneId', 'hour', 'lag_1', 'lag_2', 'rolling_mean']]
y = final_df['trolley_count']